#!/usr/bin/env bash

if [ "$ANTHROPIC_AUTH_TOKEN" == "" ]; then
    echo "\$ANTHROPIC_AUTH_TOKEN is unset!"
    exit 1
fi

export ANTHROPIC_BASE_URL=https://api.deepseek.com/ANTHROPIC_MODEL
export ANTHROPIC_AUTH_TOKEN="$ANTHROPIC_AUTH_TOKEN"
export ANTHROPIC_MODEL=deepseek-v4-pro[1m]
export ANTHROPIC_DEFAULT_OPUS_MODEL=deepseek-v4-pro[1m]
export ANTHROPIC_DEFAULT_SONNET_MODEL=deepseek-v4-pro[1m]
export ANTHROPIC_DEFAULT_HAIKU_MODEL=deepseek-v4-flash
export CLAUDE_CODE_SUBAGENT_MODEL=deepseek-v4-flash
export CLAUDE_CODE_EFFORT_LEVEL=max

claude
